"""initial - create analysis_records table

Revision ID: 0001
Revises:
Create Date: 2026-07-09 23:01:38.659293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_records_id'), 'analysis_records', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_records_project_name'), 'analysis_records', ['project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_records_project_name'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_id'), table_name='analysis_records')
    op.drop_table('analysis_records')
    # ### end Alembic commands ###
